// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Valor.Models;

#nullable disable

namespace ValorOil.Migrations
{
    [DbContext(typeof(ValorContext))]
    partial class ValorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("Valor.Models.Operator", b =>
                {
                    b.Property<int>("OperatorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator_FirstName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operator_LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("OperatorID");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Valor.Models.Report", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportParagraph")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WellID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReportID");

                    b.HasIndex("WellID");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Valor.Models.Well", b =>
                {
                    b.Property<int>("WellID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Flow_Rate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OperatorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Storage_Capacity")
                        .HasColumnType("TEXT");

                    b.Property<string>("Well_Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("WellID");

                    b.HasIndex("OperatorID");

                    b.ToTable("Wells");
                });

            modelBuilder.Entity("Valor.Models.Report", b =>
                {
                    b.HasOne("Valor.Models.Well", "Well")
                        .WithMany("Reports")
                        .HasForeignKey("WellID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Well");
                });

            modelBuilder.Entity("Valor.Models.Well", b =>
                {
                    b.HasOne("Valor.Models.Operator", "Operator")
                        .WithMany("Wells")
                        .HasForeignKey("OperatorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Valor.Models.Operator", b =>
                {
                    b.Navigation("Wells");
                });

            modelBuilder.Entity("Valor.Models.Well", b =>
                {
                    b.Navigation("Reports");
                });
#pragma warning restore 612, 618
        }
    }
}
